name: CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Simular deploy
        run: |
          echo "Iniciando processo de deploy..."
          echo "Aplicação do projeto-devops foi publicada com sucesso!"
