name: CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          # pip install -r requirements.txt  # Descomente se tiver um arquivo de dependências

      - name: Executar testes
        run: |
          pytest --maxfail=1 --disable-warnings -q
          
      - name: Simular deploy
        run: |
          echo "Iniciando processo de deploy..."
          echo "Aplicação do projeto-devops foi publicada com sucesso!"
