name: Testes Unitários com Pytest

on:
  pull_request:
    branches:
      - main  

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Listar arquivos no diretório
        run: ls -la

      - name: Mostrar conteúdo do requirements.txt
        run: cat requirements.txt

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' 

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar testes com pytest
        run: |
          pytest
