name: Testes Unitários

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out o código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar os testes
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Enviar alerta para o Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content":"🚨 Testes Unitários finalizados para o Pull Request! Confira o resultado no GitHub."}' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
